#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_TITLE "Snake Game"
// #define FPS 30
// #define FRAME_TARGET_TIME (1000 / FPS)

#define SNAKE_HEAD_SIZE 40
#define SNAKE_STEP SNAKE_HEAD_SIZE

#define BORDER_THICKNESS SNAKE_HEAD_SIZE
#define BORDER_MIN_X (BORDER_THICKNESS)
#define BORDER_MAX_X (WINDOW_WIDTH - (BORDER_THICKNESS * 2))
#define BORDER_MIN_Y (BORDER_THICKNESS)
#define BORDER_MAX_Y (WINDOW_HEIGHT - (BORDER_THICKNESS * 2))
